### ISSUE TITLE
TocForUniversalViewer: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by bonsdawende** [JBPressac/TocForUniversalViewer#1]
Hi,
I installed the two plugins TocForUniversalViewer and UniversalViewer. 
I got some error when in UniversalViewer Configuration I checked this option "**Append to "Items browse**". 

Here are the Errors, I have encountered:
bundle.min.js:4 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.Deserialiser.parse (bundle.min.js:4)
    at Object.create (bundle.min.js:5)
    at Bootstrapper._loaded (bundle.min.js:9)
    at bundle.min.js:9

When I checked the log file I had : 
PHP message: PHP Notice:  Undefined property: Theme::$support_link in /app/admin/themes/default/themes/browse.php on line 50" while reading response header from upstream, client: 1$
2018/09/26 12:08:24 [error] 10#10: *343 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: record in /app/plugins/TocForUniversalViewer/TocForUniversalViewerPlugin$
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getFiles() on null in /app/plugins/TocForUniversalViewer/TocForUniversalViewerPlugin.php:41

Can you help me please.
Thanks

**Comment by JBPressac** [comment]
Hello,
I reproduced the bug. I will need some time to find its cause. 
Thanks,

**Comment by JBPressac** [comment]
Hello,
I guess problem is solved with version 1.0.1 of the plugin. Could you confirm it ?
Thanks,

**Comment by bonsdawende** [comment]
Hello,
I confirm that your fix works well. Thank you for your help

**Comment by JBPressac** [comment]
Merci d'avoir signalé le bug. Bonne utilisation du plugin.
